sudo: false
language: elixir
elixir:
  - 1.6.6
  - 1.7.4
otp_release:
  - 20.3
  - 21.1
env:
  - MIX_ENV=test
script:
  - mix deps.compile
  - mix compile
  - mix format --check-formatted
  - mix test
